create database ElectricVehicle;

create table Users(
CustomerID varchar(50) primary key,
Name varchar(100),
Gender varchar(50),
Age int,
Job varchar(100),
LoginDate date,
LastUsed date,
Contact bigint
);

COPY Users
FROM 'C:\EV\customer_data.csv' 
DELIMITER ',' 
CSV HEADER;

select * from Users;

create table Rides(
CustomerID  varchar(50),
Date date,
Day varchar(50),
Time time, 
City varchar(50),
State varchar(50),
PickupLocation varchar(100),
DestinationLocation varchar(100),
KM decimal,
VehicleCategory Varchar(100),
AmountPaid decimal,
Latitude decimal,
Longitude decimal,
PostalCode int,
foreign key (CustomerID) references Users(CustomerID)
);

COPY Rides
FROM 'C:\EV\ola_electric_rides_data.csv' 
DELIMITER ',' 
CSV HEADER;

select * from Rides;

-- Find the total amount spent by each customer --
select customerid, sum(amountpaid) as TotalAmount from Rides
group by customerid;

--  Get the average number of kilometers traveled per ride for each customer --
select customerid, avg(km) as AverageKMTraveled from Rides
group by customerid;

-- Find customers who haven’t used the service for more than 30 days --
select Name from Users
where lastused < now() - interval '30 day';

-- Get the total number of rides for each day of the week --
select day, count(*) as TotalRides from Rides
group by day;

-- List customers who spent more than 450 amount in a single ride --
select customerid, amountpaid from rides
where amountpaid > 450;

-- Find the most common pickup and destination locations --
select pickuplocation, destinationlocation, count(*) as rides
from rides
group by pickuplocation, destinationlocation
order by rides desc;

-- Find customers who have used the service in more than one city --
select customerid, count(distinct city) as citycount from rides 
group by customerid
having count(distinct city) > 1;

-- Calculate the total distance traveled and total amount paid by customers in each city --
select city, sum(km) as TotalDistance, sum(amountpaid) as TotalPaidAmount
from rides
group by city;

-- List the top 5 customers who travel the most kilometers --
select customerid, sum(km) as totalkm from rides
group by customerid
order by totalkm desc
limit 5;

-- Find the total revenue generated by each vehicle category --
select vehiclecategory, sum(amountpaid) as totalrevenue from rides
group by vehiclecategory;






